packages:
  - 'sanity-studio'
allowBuilds:
  bcrypt: true
  core-js: false
  esbuild: true
  sharp: true
  unrs-resolver: true
overrides:
  '@types/react': 19.2.14
  '@types/react-dom': 19.2.3
  swr: 2.2.1
  axios: 1.4.0
patchedDependencies:
  react-markdown@8.0.7: patches/react-markdown@8.0.7.patch
