/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Portfolio = {
  _id: string;
  _type: 'portfolio';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  author?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'user';
  };
  skills?: Array<string>;
  introduce?: string;
  businessExperiences?: Array<{
    name?: string;
    startDate?: string;
    endDate?: string;
    holding?: boolean;
    content?: string;
    _type: 'business';
    _key: string;
  }>;
  projects?: Array<{
    name?: string;
    image?: string;
    link?: string;
    startDate?: string;
    endDate?: string;
    holding?: boolean;
    content?: string;
    _type: 'project';
    _key: string;
  }>;
  educations?: Array<{
    name?: string;
    startDate?: string;
    endDate?: string;
    holding?: boolean;
    content?: string;
    _type: 'education';
    _key: string;
  }>;
};

export type Log = {
  _id: string;
  _type: 'log';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  author?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'user';
  };
  title?: string;
  content?: string;
  photo?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  emotion?: string;
  date?: string;
  likes?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'user';
  }>;
};

export type Tag = {
  _id: string;
  _type: 'tag';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  tagName?: string;
};

export type Post = {
  _id: string;
  _type: 'post';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  author?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'user';
  };
  title?: string;
  publishedAt?: string;
  description?: string;
  pinned?: boolean;
  mainImage?: string;
  likes?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'user';
  }>;
  tags?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'tag';
  }>;
  content?: string;
  comments?: Array<
    | {
        deleted?: boolean;
        author?: {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'user';
        };
        comment?: string;
        createdAt?: string;
        comments?: Array<
          | {
              deleted?: boolean;
              author?: {
                _ref: string;
                _type: 'reference';
                _weak?: boolean;
                [internalGroqTypeReferenceTo]?: 'user';
              };
              comment?: string;
              createdAt?: string;
              _type: 'loggedInUserComment';
              _key: string;
            }
          | {
              deleted?: boolean;
              name?: string;
              password?: string;
              comment?: string;
              createdAt?: string;
              _type: 'guestComment';
              _key: string;
            }
        >;
        _type: 'loggedInUserComment';
        _key: string;
      }
    | {
        deleted?: boolean;
        name?: string;
        password?: string;
        comment?: string;
        createdAt?: string;
        comments?: Array<
          | {
              deleted?: boolean;
              author?: {
                _ref: string;
                _type: 'reference';
                _weak?: boolean;
                [internalGroqTypeReferenceTo]?: 'user';
              };
              comment?: string;
              createdAt?: string;
              _type: 'loggedInUserComment';
              _key: string;
            }
          | {
              deleted?: boolean;
              name?: string;
              password?: string;
              comment?: string;
              createdAt?: string;
              _type: 'guestComment';
              _key: string;
            }
        >;
        _type: 'guestComment';
        _key: string;
      }
  >;
};

export type User = {
  _id: string;
  _type: 'user';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  username?: string;
  name?: string;
  email?: string;
  password?: string;
  image?: string;
  blogName?: string;
  title?: string;
  introduce?: string;
  links?: {
    github?: string;
    email?: string;
    twitter?: string;
    facebook?: string;
    youtube?: string;
    homePage?: string;
  };
  following?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'user';
  }>;
  followers?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'user';
  }>;
  bookmarks?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'post';
  }>;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes =
  | Portfolio
  | Log
  | Tag
  | Post
  | User
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityImageAsset
  | SanityImageMetadata
  | Geopoint
  | Slug
  | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/service/comment.ts
// Variable: postCommentsQuery
// Query: *[_type == "post" && _id == $postId][0]{    "comments": comments[]{       createdAt,  deleted,  "id":_key,  "comment": comment,  "type":_type,  _type == 'loggedInUserComment' => {    "username":author->username,    "image":author->image,    "authorId":author._ref  },  _type == 'guestComment' => {    "username":name  },     "recomments": comments[]{        createdAt,  deleted,  "id":_key,  "comment": comment,  "type":_type,  _type == 'loggedInUserComment' => {    "username":author->username,    "image":author->image,    "authorId":author._ref  },  _type == 'guestComment' => {    "username":name  },     } | order(createdAt desc),    } | order(createdAt desc),  }.comments
export type PostCommentsQueryResult = Array<
  | {
      createdAt: string | null;
      deleted: boolean | null;
      id: string;
      comment: string | null;
      type: 'loggedInUserComment';
      username: string | null;
      image: string | null;
      authorId: string | null;
      recomments: Array<
        | {
            createdAt: string | null;
            deleted: boolean | null;
            id: string;
            comment: string | null;
            type: 'loggedInUserComment';
            username: string | null;
            image: string | null;
            authorId: string | null;
          }
        | {
            createdAt: string | null;
            deleted: boolean | null;
            id: string;
            comment: string | null;
            type: 'guestComment';
            username: string | null;
          }
      > | null;
    }
  | {
      createdAt: string | null;
      deleted: boolean | null;
      id: string;
      comment: string | null;
      type: 'guestComment';
      username: string | null;
      recomments: Array<
        | {
            createdAt: string | null;
            deleted: boolean | null;
            id: string;
            comment: string | null;
            type: 'loggedInUserComment';
            username: string | null;
            image: string | null;
            authorId: string | null;
          }
        | {
            createdAt: string | null;
            deleted: boolean | null;
            id: string;
            comment: string | null;
            type: 'guestComment';
            username: string | null;
          }
      > | null;
    }
> | null;
// Variable: nestedCommentPasswordQuery
// Query: *[_type == "post" && _id == $postId][0]{    'password': comments[_key == $parentCommentId][0].comments[_key == $commentId][0].password  }
export type NestedCommentPasswordQueryResult = {
  password: string | null;
} | null;
// Variable: topLevelCommentPasswordQuery
// Query: *[_type == "post" && _id == $postId][0]{    'password': comments[_key == $commentId][0].password  }
export type TopLevelCommentPasswordQueryResult = {
  password: string | null;
} | null;
// Variable: nestedCommentByKeyQuery
// Query: *[_id == $postId][0].comments[_key == $parentCommentId].comments[_key == $commentId]
export type NestedCommentByKeyQueryResult = Array<
  | {
      deleted?: boolean;
      name?: string;
      password?: string;
      comment?: string;
      createdAt?: string;
      _type: 'guestComment';
      _key: string;
    }
  | {
      deleted?: boolean;
      author?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'user';
      };
      comment?: string;
      createdAt?: string;
      _type: 'loggedInUserComment';
      _key: string;
    }
  | null
> | null;
// Variable: topLevelCommentByKeyQuery
// Query: *[_id == $postId][0].comments[_key == $commentId]
export type TopLevelCommentByKeyQueryResult = Array<
  | {
      deleted?: boolean;
      name?: string;
      password?: string;
      comment?: string;
      createdAt?: string;
      comments?: Array<
        | {
            deleted?: boolean;
            name?: string;
            password?: string;
            comment?: string;
            createdAt?: string;
            _type: 'guestComment';
            _key: string;
          }
        | {
            deleted?: boolean;
            author?: {
              _ref: string;
              _type: 'reference';
              _weak?: boolean;
              [internalGroqTypeReferenceTo]?: 'user';
            };
            comment?: string;
            createdAt?: string;
            _type: 'loggedInUserComment';
            _key: string;
          }
      >;
      _type: 'guestComment';
      _key: string;
    }
  | {
      deleted?: boolean;
      author?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'user';
      };
      comment?: string;
      createdAt?: string;
      comments?: Array<
        | {
            deleted?: boolean;
            name?: string;
            password?: string;
            comment?: string;
            createdAt?: string;
            _type: 'guestComment';
            _key: string;
          }
        | {
            deleted?: boolean;
            author?: {
              _ref: string;
              _type: 'reference';
              _weak?: boolean;
              [internalGroqTypeReferenceTo]?: 'user';
            };
            comment?: string;
            createdAt?: string;
            _type: 'loggedInUserComment';
            _key: string;
          }
      >;
      _type: 'loggedInUserComment';
      _key: string;
    }
> | null;

// Source: ./src/service/posts.ts
// Variable: allPostsQuery
// Query: *[_type == "post"]| order(coalesce(publishedAt, _createdAt) desc){  title,  description,  mainImage,  pinned,  "updatedAt":_updatedAt,  "createdAt":coalesce(publishedAt, _createdAt),  "tags":tags[]->tagName,  "username":author->username,  "name":author->name,  "userImage":author->image,  "likes":count(likes),  "id":_id}
export type AllPostsQueryResult = Array<{
  title: string | null;
  description: string | null;
  mainImage: string | null;
  pinned: boolean | null;
  updatedAt: string;
  createdAt: string;
  tags: Array<string | null> | null;
  username: string | null;
  name: string | null;
  userImage: string | null;
  likes: number | null;
  id: string;
}>;
// Variable: userPostsQuery
// Query: *[_type == "post" && author->username == $username]| order(coalesce(publishedAt, _createdAt) desc){  title,  description,  mainImage,  pinned,  "updatedAt":_updatedAt,  "createdAt":coalesce(publishedAt, _createdAt),  "tags":tags[]->tagName,  "username":author->username,  "name":author->name,  "userImage":author->image,  "likes":count(likes),  "id":_id}
export type UserPostsQueryResult = Array<{
  title: string | null;
  description: string | null;
  mainImage: string | null;
  pinned: boolean | null;
  updatedAt: string;
  createdAt: string;
  tags: Array<string | null> | null;
  username: string | null;
  name: string | null;
  userImage: string | null;
  likes: number | null;
  id: string;
}>;
// Variable: tagPostsQuery
// Query: *[_type == 'post' && $tagName in tags[]->tagName]| order(coalesce(publishedAt, _createdAt) desc){  title,  description,  mainImage,  pinned,  "updatedAt":_updatedAt,  "createdAt":coalesce(publishedAt, _createdAt),  "tags":tags[]->tagName,  "username":author->username,  "name":author->name,  "userImage":author->image,  "likes":count(likes),  "id":_id}
export type TagPostsQueryResult = Array<{
  title: string | null;
  description: string | null;
  mainImage: string | null;
  pinned: boolean | null;
  updatedAt: string;
  createdAt: string;
  tags: Array<string | null> | null;
  username: string | null;
  name: string | null;
  userImage: string | null;
  likes: number | null;
  id: string;
}>;
// Variable: bookmarkPostsQuery
// Query: *[_type == "post" && _id in *[_type == "user" && username == $username].bookmarks[]._ref]  | order(coalesce(publishedAt, _createdAt) desc){  title,  description,  mainImage,  pinned,  "updatedAt":_updatedAt,  "createdAt":coalesce(publishedAt, _createdAt),  "tags":tags[]->tagName,  "username":author->username,  "name":author->name,  "userImage":author->image,  "likes":count(likes),  "id":_id}
export type BookmarkPostsQueryResult = Array<{
  title: string | null;
  description: string | null;
  mainImage: string | null;
  pinned: boolean | null;
  updatedAt: string;
  createdAt: string;
  tags: Array<string | null> | null;
  username: string | null;
  name: string | null;
  userImage: string | null;
  likes: number | null;
  id: string;
}>;
// Variable: userTagPostsQuery
// Query: *[_type == 'post' && author->username == $username && $tagName in tags[]->tagName]| order(coalesce(publishedAt, _createdAt) desc){  title,  description,  mainImage,  pinned,  "updatedAt":_updatedAt,  "createdAt":coalesce(publishedAt, _createdAt),  "tags":tags[]->tagName,  "username":author->username,  "name":author->name,  "userImage":author->image,  "likes":count(likes),  "id":_id}
export type UserTagPostsQueryResult = Array<{
  title: string | null;
  description: string | null;
  mainImage: string | null;
  pinned: boolean | null;
  updatedAt: string;
  createdAt: string;
  tags: Array<string | null> | null;
  username: string | null;
  name: string | null;
  userImage: string | null;
  likes: number | null;
  id: string;
}>;
// Variable: postDetailQuery
// Query: *[_type == "post" && _id == $postId][0]{    'currentPost': {  ...,  "tags":tags[]->tagName,  "updatedAt":_updatedAt,  "createdAt":coalesce(publishedAt, _createdAt),  "username":author->username,  "userImage":author->image,  "authorId":author._ref,  "likes":likes[]._ref,  "id":_id},    'nextPost': *[_type == 'post' && author->username == $username && coalesce(publishedAt, _createdAt) < coalesce(^.publishedAt, ^._createdAt)][0]{ "username":author->username, title, "id":_id},    'previousPost': *[_type == 'post' && author->username == $username && coalesce(publishedAt, _createdAt) > coalesce(^.publishedAt, ^._createdAt)] | order(coalesce(publishedAt, _createdAt) asc)[0]{ "username":author->username, title, "id":_id}  }
export type PostDetailQueryResult = {
  currentPost: {
    _id: string;
    _type: 'post';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    author?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'user';
    };
    title?: string;
    publishedAt?: string;
    description?: string;
    pinned?: boolean;
    mainImage?: string;
    likes: Array<string> | null;
    tags: Array<string | null> | null;
    content?: string;
    comments?: Array<
      | {
          deleted?: boolean;
          name?: string;
          password?: string;
          comment?: string;
          createdAt?: string;
          comments?: Array<
            | {
                deleted?: boolean;
                name?: string;
                password?: string;
                comment?: string;
                createdAt?: string;
                _type: 'guestComment';
                _key: string;
              }
            | {
                deleted?: boolean;
                author?: {
                  _ref: string;
                  _type: 'reference';
                  _weak?: boolean;
                  [internalGroqTypeReferenceTo]?: 'user';
                };
                comment?: string;
                createdAt?: string;
                _type: 'loggedInUserComment';
                _key: string;
              }
          >;
          _type: 'guestComment';
          _key: string;
        }
      | {
          deleted?: boolean;
          author?: {
            _ref: string;
            _type: 'reference';
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: 'user';
          };
          comment?: string;
          createdAt?: string;
          comments?: Array<
            | {
                deleted?: boolean;
                name?: string;
                password?: string;
                comment?: string;
                createdAt?: string;
                _type: 'guestComment';
                _key: string;
              }
            | {
                deleted?: boolean;
                author?: {
                  _ref: string;
                  _type: 'reference';
                  _weak?: boolean;
                  [internalGroqTypeReferenceTo]?: 'user';
                };
                comment?: string;
                createdAt?: string;
                _type: 'loggedInUserComment';
                _key: string;
              }
          >;
          _type: 'loggedInUserComment';
          _key: string;
        }
    >;
    updatedAt: string;
    createdAt: string;
    username: string | null;
    userImage: string | null;
    authorId: string | null;
    id: string;
  };
  nextPost: {
    username: string | null;
    title: string | null;
    id: string;
  } | null;
  previousPost: {
    username: string | null;
    title: string | null;
    id: string;
  } | null;
} | null;
// Variable: existingTagQuery
// Query: *[_type == "tag" && tagName == $tagName]
export type ExistingTagQueryResult = Array<{
  _id: string;
  _type: 'tag';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  tagName?: string;
}>;
// Variable: userPostTagsQuery
// Query: *[_type == 'post' && author->username == $username].tags[]->tagName
export type UserPostTagsQueryResult = Array<string | null>;
// Variable: postAuthorQuery
// Query: *[_type == "post" && _id == $postId][0]{ "authorId": author->_id }
export type PostAuthorQueryResult = {
  authorId: string | null;
} | null;

// Source: ./src/service/user.ts
// Variable: checkUsernameValidQuery
// Query: *[_type=='user' && username == $username][0]
export type CheckUsernameValidQueryResult = {
  _id: string;
  _type: 'user';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  username?: string;
  name?: string;
  email?: string;
  password?: string;
  image?: string;
  blogName?: string;
  title?: string;
  introduce?: string;
  links?: {
    github?: string;
    email?: string;
    twitter?: string;
    facebook?: string;
    youtube?: string;
    homePage?: string;
  };
  following?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'user';
  }>;
  followers?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'user';
  }>;
  bookmarks?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'post';
  }>;
} | null;
// Variable: checkEmailValidQuery
// Query: *[_type=='user' && email == $email][0]
export type CheckEmailValidQueryResult = {
  _id: string;
  _type: 'user';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  username?: string;
  name?: string;
  email?: string;
  password?: string;
  image?: string;
  blogName?: string;
  title?: string;
  introduce?: string;
  links?: {
    github?: string;
    email?: string;
    twitter?: string;
    facebook?: string;
    youtube?: string;
    homePage?: string;
  };
  following?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'user';
  }>;
  followers?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'user';
  }>;
  bookmarks?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'post';
  }>;
} | null;
// Variable: loginWithEmailQuery
// Query: *[_type=='user' && email == $email][0]{    "id":_id,    email,    name,    username,    password,    image,  }
export type LoginWithEmailQueryResult = {
  id: string;
  email: string | null;
  name: string | null;
  username: string | null;
  password: string | null;
  image: string | null;
} | null;
// Variable: userDataQuery
// Query: *[_type=='user' && _id == $userId][0]  {"id":_id,name,username,email,image,blogName}
export type UserDataQueryResult = {
  id: string;
  name: string | null;
  username: string | null;
  email: string | null;
  image: string | null;
  blogName: string | null;
} | null;
// Variable: userByUsernameQuery
// Query: *[_type == "user" && username == $username][0]{    ...,    "id":_id,    following[]->{"id":_id,username,name,image,title},    followers[]->{"id":_id,username,name,image,title},    "bookmarks":bookmarks[]->_id  }
export type UserByUsernameQueryResult = {
  _id: string;
  _type: 'user';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  username?: string;
  name?: string;
  email?: string;
  password?: string;
  image?: string;
  blogName?: string;
  title?: string;
  introduce?: string;
  links?: {
    github?: string;
    email?: string;
    twitter?: string;
    facebook?: string;
    youtube?: string;
    homePage?: string;
  };
  following: Array<{
    id: string;
    username: string | null;
    name: string | null;
    image: string | null;
    title: string | null;
  }> | null;
  followers: Array<{
    id: string;
    username: string | null;
    name: string | null;
    image: string | null;
    title: string | null;
  }> | null;
  bookmarks: Array<string> | null;
  id: string;
} | null;
// Variable: userForProfileQuery
// Query: *[_type=='user' && username == $username][0]{    ...,    "id":_id,    "following":count(following),    "followers":count(followers),    "posts":count(*[_type=="post" && author->username == $username])  }
export type UserForProfileQueryResult = {
  _id: string;
  _type: 'user';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  username?: string;
  name?: string;
  email?: string;
  password?: string;
  image?: string;
  blogName?: string;
  title?: string;
  introduce?: string;
  links?: {
    github?: string;
    email?: string;
    twitter?: string;
    facebook?: string;
    youtube?: string;
    homePage?: string;
  };
  following: number | null;
  followers: number | null;
  bookmarks?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'post';
  }>;
  id: string;
  posts: number;
} | null;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
  interface SanityQueries {
    '\n  *[_type == "post" && _id == $postId][0]{\n    "comments": comments[]{\n     \n  createdAt,\n  deleted,\n  "id":_key,\n  "comment": comment,\n  "type":_type,\n  _type == \'loggedInUserComment\' => {\n    "username":author->username,\n    "image":author->image,\n    "authorId":author._ref\n  },\n  _type == \'guestComment\' => {\n    "username":name\n  },\n\n     "recomments": comments[]{\n      \n  createdAt,\n  deleted,\n  "id":_key,\n  "comment": comment,\n  "type":_type,\n  _type == \'loggedInUserComment\' => {\n    "username":author->username,\n    "image":author->image,\n    "authorId":author._ref\n  },\n  _type == \'guestComment\' => {\n    "username":name\n  },\n\n     } | order(createdAt desc),\n    } | order(createdAt desc),\n  }.comments\n': PostCommentsQueryResult;
    '\n  *[_type == "post" && _id == $postId][0]{\n    \'password\': comments[_key == $parentCommentId][0].comments[_key == $commentId][0].password\n  }\n': NestedCommentPasswordQueryResult;
    '\n  *[_type == "post" && _id == $postId][0]{\n    \'password\': comments[_key == $commentId][0].password\n  }\n': TopLevelCommentPasswordQueryResult;
    '\n  *[_id == $postId][0].comments[_key == $parentCommentId].comments[_key == $commentId]\n': NestedCommentByKeyQueryResult;
    '\n  *[_id == $postId][0].comments[_key == $commentId]\n': TopLevelCommentByKeyQueryResult;
    '\n  *[_type == "post"]| order(coalesce(publishedAt, _createdAt) desc){\n  title,\n  description,\n  mainImage,\n  pinned,\n  "updatedAt":_updatedAt,\n  "createdAt":coalesce(publishedAt, _createdAt),\n  "tags":tags[]->tagName,\n  "username":author->username,\n  "name":author->name,\n  "userImage":author->image,\n  "likes":count(likes),\n  "id":_id\n}\n': AllPostsQueryResult;
    '\n  *[_type == "post" && author->username == $username]| order(coalesce(publishedAt, _createdAt) desc){\n  title,\n  description,\n  mainImage,\n  pinned,\n  "updatedAt":_updatedAt,\n  "createdAt":coalesce(publishedAt, _createdAt),\n  "tags":tags[]->tagName,\n  "username":author->username,\n  "name":author->name,\n  "userImage":author->image,\n  "likes":count(likes),\n  "id":_id\n}\n': UserPostsQueryResult;
    '\n  *[_type == \'post\' && $tagName in tags[]->tagName]| order(coalesce(publishedAt, _createdAt) desc){\n  title,\n  description,\n  mainImage,\n  pinned,\n  "updatedAt":_updatedAt,\n  "createdAt":coalesce(publishedAt, _createdAt),\n  "tags":tags[]->tagName,\n  "username":author->username,\n  "name":author->name,\n  "userImage":author->image,\n  "likes":count(likes),\n  "id":_id\n}\n': TagPostsQueryResult;
    '\n  *[_type == "post" && _id in *[_type == "user" && username == $username].bookmarks[]._ref]\n  | order(coalesce(publishedAt, _createdAt) desc){\n  title,\n  description,\n  mainImage,\n  pinned,\n  "updatedAt":_updatedAt,\n  "createdAt":coalesce(publishedAt, _createdAt),\n  "tags":tags[]->tagName,\n  "username":author->username,\n  "name":author->name,\n  "userImage":author->image,\n  "likes":count(likes),\n  "id":_id\n}\n': BookmarkPostsQueryResult;
    '\n  *[_type == \'post\' && author->username == $username && $tagName in tags[]->tagName]| order(coalesce(publishedAt, _createdAt) desc){\n  title,\n  description,\n  mainImage,\n  pinned,\n  "updatedAt":_updatedAt,\n  "createdAt":coalesce(publishedAt, _createdAt),\n  "tags":tags[]->tagName,\n  "username":author->username,\n  "name":author->name,\n  "userImage":author->image,\n  "likes":count(likes),\n  "id":_id\n}\n': UserTagPostsQueryResult;
    '\n  *[_type == "post" && _id == $postId][0]{\n    \'currentPost\': {\n  ...,\n  "tags":tags[]->tagName,\n  "updatedAt":_updatedAt,\n  "createdAt":coalesce(publishedAt, _createdAt),\n  "username":author->username,\n  "userImage":author->image,\n  "authorId":author._ref,\n  "likes":likes[]._ref,\n  "id":_id\n},\n    \'nextPost\': *[_type == \'post\' && author->username == $username && coalesce(publishedAt, _createdAt) < coalesce(^.publishedAt, ^._createdAt)][0]{ "username":author->username, title, "id":_id},\n    \'previousPost\': *[_type == \'post\' && author->username == $username && coalesce(publishedAt, _createdAt) > coalesce(^.publishedAt, ^._createdAt)] | order(coalesce(publishedAt, _createdAt) asc)[0]{ "username":author->username, title, "id":_id}\n  }\n': PostDetailQueryResult;
    '\n  *[_type == "tag" && tagName == $tagName]\n': ExistingTagQueryResult;
    "\n  *[_type == 'post' && author->username == $username].tags[]->tagName\n": UserPostTagsQueryResult;
    '\n  *[_type == "post" && _id == $postId][0]{ "authorId": author->_id }\n': PostAuthorQueryResult;
    "\n  *[_type=='user' && username == $username][0]\n": CheckUsernameValidQueryResult;
    "\n  *[_type=='user' && email == $email][0]\n": CheckEmailValidQueryResult;
    '\n  *[_type==\'user\' && email == $email][0]{\n    "id":_id,\n    email,\n    name,\n    username,\n    password,\n    image,\n  }\n': LoginWithEmailQueryResult;
    '\n  *[_type==\'user\' && _id == $userId][0]\n  {"id":_id,name,username,email,image,blogName}\n': UserDataQueryResult;
    '\n  *[_type == "user" && username == $username][0]{\n    ...,\n    "id":_id,\n    following[]->{"id":_id,username,name,image,title},\n    followers[]->{"id":_id,username,name,image,title},\n    "bookmarks":bookmarks[]->_id\n  }\n': UserByUsernameQueryResult;
    '\n  *[_type==\'user\' && username == $username][0]{\n    ...,\n    "id":_id,\n    "following":count(following),\n    "followers":count(followers),\n    "posts":count(*[_type=="post" && author->username == $username])\n  }\n': UserForProfileQueryResult;
  }
}
